workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "saas"

include:
  - project: 'dn-sied/ci-config'
    file: '/.gitlab-ci-template-container-image.yml'

variables:
  MAVEN_IMAGE: maven:3-jdk-11
  MAVEN_ADDITIONAL_CLI_OPTS: "-Pcoverage,production"